WIP: Use the new from_dataset method to initialize objects in examples.
richford/AFQ-Insight pull request #123
Opened 2022-06-23 23:08 UTC by arokem

Follow up on #121.

TODO: 
- [ ] Find all the examples that currently load these datasets in a few steps.
- [ ] It's nice to have this method, but we will also want there to be an example that shows how to load your own data from CSV files step by step. 
- [ ] Mention somewhere that these CSVs are generated and point to pyAFQ and file-format spec.

2022-06-25 12:18 UTC, richford commented on examples/plot_hbn_site_profiles.py
> +# We can pass the :class:`AFQDataset` class instance to Sckit Learn's
```suggestion
# We can pass the :class:`AFQDataset` class instance to scikit-learn's
```

Just to copy how they refer to scikit-learn in their own docs.

2022-06-27 21:58 UTC, arokem commented
This is ready for a review.

2022-06-27 22:00 UTC, richford commented
There are some flake8 errors on build (3.9), mostly due to unused imports.

2022-06-28 03:45 UTC, richford requested changes
LGTM, with one small comment. There is an explanation that worked well with the `afqdata` `namedtumple` returned by `load_sarica` but not with the `AFQDataset` instance.

2022-06-28 03:45 UTC, richford commented on examples/plot_als_classification.py
>  # unpacking the tuple. To see all of the available fields use `afqdata._fields`
```suggestion
# ``afqdata`` is an ``AFQDataset`` object, with properties corresponding to the tractometry features and phenotypic targets.
```

2022-06-28 10:55 UTC, merged