WIP: Convolutional neural network models
richford/AFQ-Insight pull request #72
Opened 2021-05-13 22:18 UTC by arokem

2021-06-14 22:11 UTC, richford requested changes
Great work! I made some comments line-by-line. I'd recommend making a `BaseCNN` class that inherits from `BaseEstimator` and then defining two subclasses `CNNClassifier` and `CNNRegressor` that inherit from `ClassifierMixin` and `RegressorMixin`, respectively.

2021-06-14 22:11 UTC, richford commented on afqinsight/cnn.py
> +	def fit(self, X, y, X_test, y_test):
The inclusion of `X_test` and `y_test` here isn't quite in line with the sklearn estimator API. You could specify the percentage of `X` that you want to use for the test set and pass that through to `ModelBuilder`. Or you could call `train_test_split` here. And for reproducibility, you could add a `random_state` parameter to the class `__init__` and pass that into `train_test_split`.

2021-06-14 22:11 UTC, richford commented on afqinsight/cnn.py
> +			X, y = self._preprocess(X, y)
I think this cold be moved out of the `else` clause. The `if` block will raise an error, so anything that happens after that can proceed as normal.

2021-06-14 22:11 UTC, richford commented on afqinsight/cnn.py
> +	def score(self, y_test, y_hat):
If you inherit from `RegressorMixin` or `ClassifierMixin` then it will already have a `score` method.

2021-06-14 22:11 UTC, richford commented on afqinsight/cnn.py
> +		nan_mask = np.logical_not(np.isnan(y_test))
Not sure I understand the requirement for the `NaN` check here. Could you help me understand?

2021-06-14 22:11 UTC, richford commented on afqinsight/tests/test_cnn.py
> +
Once the sklearn compatibility is implemented, we should add `check_estimator(CNN())` to the tests. See: https://scikit-learn.org/stable/developers/develop.html#rolling-your-own-estimator

2021-06-14 22:12 UTC, richford commented
There are a lot of files in this PR like `untitled_project/oracle.json` and `untitled_project/trial_5223582d2b335dad9cfb5a07c3126556/checkpoints/epoch_0/checkpoint.data-00000-of-00001`. It seems like these are checkpoint files from keras tuner, maybe. Are they supposed to be here or are they the byproduct of a `git add -A`?

2021-06-14 22:13 UTC, richford commented
Again, great work overall! I also think this could use some docstring improvements and maybe some more sphinx documentation and examples.

2021-06-14 23:22 UTC, richford commented
Some flake8 errors here caught by the CI. I think you might be able to fix all of these with
`black .` run from the root of the git repo.

2021-06-20 20:27 UTC, cbarnes7 commented on afqinsight/cnn.py
> +	model.add(Dense(dense_filters, activation='relu', input_shape=input_shape))
Done

2021-06-20 20:35 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(nodes) is int:
Done

2021-06-20 20:35 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(channels) is int:
Done

2021-06-20 20:35 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(layers) is int:
Done

2021-06-20 20:36 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(max_epochs) is int:
Done

2021-06-20 20:36 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(batch_size) is int:
Done

2021-06-20 20:36 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if type(tuner) is not str and tuner is not None:
Done

2021-06-20 20:36 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if not type(val_split) is float:
Done

2021-06-22 22:13 UTC, richford commented
@cbarnes7, you mentioned that you addressed some of my comments but I don't see any new commits. Did you push those to the [cbarnes7:cnn](https://github.com/cbarnes7/AFQ-Insight/tree/cnn) branch?

2021-06-24 22:19 UTC, cbarnes7 commented on afqinsight/cnn.py
> +from tensorflow.keras.models import Sequential
done

2021-06-24 22:19 UTC, cbarnes7 commented on afqinsight/cnn.py
> +	def fit(self, X, y, X_test, y_test):
done

2021-06-24 22:22 UTC, cbarnes7 commented on afqinsight/cnn.py
> +			X, y = self._preprocess(X, y)
done

2021-06-24 22:32 UTC, cbarnes7 commented
> @cbarnes7, you mentioned that you addressed some of my comments but I don't see any new commits. Did you push those to the [cbarnes7:cnn](https://github.com/cbarnes7/AFQ-Insight/tree/cnn) branch?

@richford I just pushed a few of the smaller changes. still working through them

2021-06-24 23:10 UTC, arokem commented
@cbarnes7 : I think that you still need to run something like `git push origin cnn` to get the newer commits into the PR.

2021-06-25 13:55 UTC, cbarnes7 commented
@arokem @richford I did push using `git push origin cnn` but I have bad service (on a roadtrip) so it may not have gone through… I’ll let you know when I’m able to push again

2021-06-25 15:58 UTC, cbarnes7 commented on afqinsight/cnn.py
> +	def __init__(self, nodes, channels, max_epochs=50, batch_size=32, tuner=None, layers=1, val_split=0.2, **tuner_kwargs):
@richford since we aren't making this fully sklearn-compatible, should i adjust __init__ so it doesn't contain logic? or is it fine as is for now?

2021-06-25 16:24 UTC, richford commented on afqinsight/cnn.py
> +class CNN:
Nevermind. We decided to either ignore or postpone an sklearn-compatible API.

2021-06-25 16:25 UTC, richford commented on afqinsight/cnn.py
> +	def _preprocess(self, X, y=None):
Nevermind, see above comment about postponing or ignoring the sklearn-compatible API.

2021-06-25 16:25 UTC, richford commented on afqinsight/cnn.py
> +	def score(self, y_test, y_hat):
Ignore. We're postponing or ignoring the sklearn-compatible API.

2021-06-25 16:26 UTC, richford commented on afqinsight/tests/test_cnn.py
> +
Ignore this

2021-06-25 16:27 UTC, richford commented on afqinsight/cnn.py
> +	def __init__(self, nodes, channels, max_epochs=50, batch_size=32, tuner=None, layers=1, val_split=0.2, **tuner_kwargs):
It's fine as is now.

2021-06-25 16:30 UTC, richford commented on afqinsight/cnn.py
> +
```suggestion
```

Suggest getting rid of these docstrings lines now that you've gotten rid of the input parameters.

2021-06-25 17:03 UTC, richford commented on afqinsight/cnn.py
> +from tensorflow.keras.models import Sequential
@cbarnes7, thanks! However, I don't see `_check_keras()` being called anywhere by any of the other classes.

2021-06-25 17:08 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		imp = SimpleImputer(strategy='median')
done

2021-06-25 17:23 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		subjects = X.shape[0]
@richford n_subjects is declared by `n_subjects = X.shape[0]` so that would always be correct, but where is n_features coming from?

2021-06-25 17:28 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		if self.nodes * self.channels != X.shape[1]:
done

2021-06-25 17:30 UTC, cbarnes7 commented on afqinsight/cnn.py
> +
done

2021-06-25 17:33 UTC, richford commented on afqinsight/cnn.py
> +		subjects = X.shape[0]
I was suggesting doing
```
n_samples, n_features = X.shape
```
instead of
```
n_subjects = X.shape[0]
```
This would unpack the tuple returned by `X.shape` so that we can get `n_samples` and `n_features` all in one line. Then later, we can check that
`n_features == self.n_nodes * self.n_channels`

2021-06-25 18:59 UTC, cbarnes7 commented on afqinsight/cnn.py
> +		nan_mask = np.logical_not(np.isnan(y_test))
I think the weston haven's or cam-can data had a nan in it and was causing super weird errors in testing that took Ariel and I a long time to trace back to a nan. We decided to add this in to address it. We could get rid of this though and instead check for NaNs and raise a cleaner error if there are any depending on what you think.

2021-07-19 20:23 UTC, richford commented
Closing in favor of #83

2021-07-19 20:23 UTC, closed without merging